services:
  db:
    image: postgres:16
    container_name: ts_db
    environment:
      POSTGRES_USER: ts
      POSTGRES_PASSWORD: ts
      POSTGRES_DB: ts
    ports:
      - "5432:5432"
    volumes:
      - ts_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ts -d ts"]
      interval: 5s
      timeout: 3s
      retries: 20
  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    environment:
      DATABASE_URL: postgresql://ts:ts@db:5432/ts
    depends_on:
      db:
        condition: service_healthy
  pipeline_hourly:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    environment:
      DATABASE_URL: postgresql://ts:ts@db:5432/ts
    depends_on:
      db:
        condition: service_healthy
    command:
      [
        "/bin/sh",
        "-c",
        "python -m src.pipeline.build_hourly_returns; while sleep 3600; do python -m src.pipeline.build_hourly_returns; done",
      ]
    restart: unless-stopped
  pipeline_daily:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    environment:
      DATABASE_URL: postgresql://ts:ts@db:5432/ts
    depends_on:
      db:
        condition: service_healthy
    command:
      [
        "/bin/sh",
        "-c",
        "python -m src.pipeline.build_daily_returns; while sleep 86400; do python -m src.pipeline.build_daily_returns; done",
      ]
    restart: unless-stopped



volumes:
  ts_pgdata:
